### ISSUE TITLE
Book Name?

### ISSUE THREAD

**Issue by henrytirla** [blueletter123456789/book-algo-data-structure#1]
Can you please share the book you are reading for this repository

**Comment by blueletter123456789** [comment]
I refer to the following book.
[問題解決力を鍛える！アルゴリズムとデータ構造 (ＫＳ情報科学専門書)](https://www.amazon.co.jp/%E5%95%8F%E9%A1%8C%E8%A7%A3%E6%B1%BA%E5%8A%9B%E3%82%92%E9%8D%9B%E3%81%88%E3%82%8B%EF%BC%81%E3%82%A2%E3%83%AB%E3%82%B4%E3%83%AA%E3%82%BA%E3%83%A0%E3%81%A8%E3%83%87%E3%83%BC%E3%82%BF%E6%A7%8B%E9%80%A0-%EF%BC%AB%EF%BC%B3%E6%83%85%E5%A0%B1%E7%A7%91%E5%AD%A6%E5%B0%82%E9%96%80%E6%9B%B8-%E5%A4%A7%E6%A7%BB%E5%85%BC%E8%B3%87-ebook/dp/B08PV83L3N/ref=sr_1_1?crid=34UNLZQNGCH7U&keywords=%E3%83%87%E3%83%BC%E3%82%BF%E6%A7%8B%E9%80%A0&qid=1650968235&sprefix=%2Caps%2C222&sr=8-1)

But, it is written in Japanese.
